/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('./src/elements/ElAlert/ElAlert.vue')['default']
    ElAlertContainer: typeof import('./src/elements/ElAlert/ElAlertContainer.vue')['default']
    ElAlertItem: typeof import('./src/elements/ElAlert/ElAlertItem.vue')['default']
    ElBreadcrumbs: typeof import('./src/elements/ElBreadcrumbs.vue')['default']
    ElButton: typeof import('./src/elements/ElButton.vue')['default']
    ElContainer: typeof import('./src/elements/ElContainer.vue')['default']
    ElDrawer: typeof import('./src/elements/ElDrawer.vue')['default']
    ElForm: typeof import('./src/elements/ElForm.vue')['default']
    ElMenu: typeof import('./src/elements/ElMenu.vue')['default']
    ElModal: typeof import('./src/elements/ElModal.vue')['default']
    ElSheet: typeof import('./src/elements/ElSheet.vue')['default']
    ElSlideGroup: typeof import('./src/elements/ElSlide/ElSlideGroup.vue')['default']
    ElSlideGroupItem: typeof import('./src/elements/ElSlide/ElSlideGroupItem.vue')['default']
    ElTable: typeof import('./src/elements/ElTable.vue')['default']
    ElTabs: typeof import('./src/elements/ElTabs.vue')['default']
    ElText: typeof import('./src/elements/ElText.vue')['default']
    ElTextarea: typeof import('./src/elements/ElTextarea.vue')['default']
    ElTextField: typeof import('./src/elements/ElTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
