/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//events': RouteRecordInfo<'//events', '/events', Record<never, never>, Record<never, never>>,
    '//login': RouteRecordInfo<'//login', '/login', Record<never, never>, Record<never, never>>,
    '//my-events': RouteRecordInfo<'//my-events', '/my-events', Record<never, never>, Record<never, never>>,
    '//my-events/': RouteRecordInfo<'//my-events/', '/my-events', Record<never, never>, Record<never, never>>,
    '//my-events/[id]': RouteRecordInfo<'//my-events/[id]', '/my-events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//my-events/create': RouteRecordInfo<'//my-events/create', '/my-events/create', Record<never, never>, Record<never, never>>,
    '//my-qr': RouteRecordInfo<'//my-qr', '/my-qr', Record<never, never>, Record<never, never>>,
    '//register': RouteRecordInfo<'//register', '/register', Record<never, never>, Record<never, never>>,
  }
}
